### ISSUE TITLE
New transaction 404 error page

### ISSUE THREAD

**Issue by zillionn** [ArkEcosystem/explorer#436]
**Is your feature request related to a problem? Please describe.**
When I open a new trx link, from the mobile wallet or somewhere else, I'm redirected to `https://explorer.ark.io/404` because the trx is not yet forged. This could scare new users and also not very user friendly.

**Describe the solution you'd like**
How about to add the timestamp of the trx in the link, for example:
`https://explorer.ark.io/transaction/{trxid}?t={timestamp}`
The explorer will than check if it's a new/recent transaction and not redirect to 404 page but instead show some `waiting` screen that will check every 8-10s if the transaction is forged and redirect to it's page.

**Comment by faustbrian** [comment]
This seems like a very very niche use-case and doesn't seem like something that is reasonable because of the 8 second block times.

I also don't know how it would scare new users away since the 8 second block times and what they mean should be known within 5 minutes of reading about Ark. The blockchain has no knowledge about your transaction until it gets forged other than that it exists in some transaction pools on the network.

**Comment by boldninja** [comment]
I agree with Brian, I'd incorporate this on a client side (aka desktop wallet and mobile wallets). Some kind of toast message or disable clicking on TXID until at least 1 confirmation. With dynamic fees coming this would be even harder to do on explorer.

**Comment by zillionn** [comment]
OK, is it that hard to just add some message, that the trx is not found because it's probably not yet forged or something like that instead of showing 404 error page. Links leading to 404 pages is always a bad thing.

Also, you have it in the pool, why don't you show the transaction details even though it's with 0 confirmations, like Bitcoin explorers?
