### ISSUE TITLE
bug: totalforged hardcoded to 2 * block

### ISSUE THREAD

**Issue by ItsANameToo** [ArkEcosystem/explorer#830]
Right now, the `total forged` in the delegate monitor is hardcoded to use `2 * forged blocks` (https://github.com/ArkEcosystem/explorer/blob/develop/src/components/monitor/header/TotalForged.vue#L43), which works for ARK in its current state. However, a chain with a different reward per block will get a wrong number for `total forged`. 

Instead of using `2`, it should use the network configuration for block reward, but should also keep in mind milestones in case rewards have changed in the past.

**Comment by dated** [comment]
There is another option: subtract the total amount of the genesis block from the total supply. The main problem I see with both approaches is that milestones and genesisBlock are available only through the `node/configuration/crypto` endpoint which returns a huge chunk of data.

The genesis block approach has the advantage that the necessary value could be fetched once and stored in local storage, since it's immutable. Want me to submit a PR @ItsANameToo?

**Comment by ItsANameToo** [comment]
How will the genesisblock approach work for networks that have had multiple reward changes? In case of ARK it started with 0 and changed to 2 from a certain height, but let's say a chain started at 0, then to 5 tokens at height 1M, 3 tokens at height 2M, 2 tokens at height 3M and current height being 3.5M :thinking:

**Comment by dated** [comment]
Reward changes don't really matter with that approach, `totalSupply === genesisAmount + totalForged`.

**Comment by dated** [comment]
That equation remains true with every block forged, and there's only one unkown variable.

**Comment by ItsANameToo** [comment]
yeah you are correct, I didn't read your suggestion properly
